# https://blog.chengweichen.com/2016/04/docker-gitlab-cigitlab-runner.html
# https://docs.gitlab.com/omnibus/docker/#install-gitlab-using-docker-compose

version: '3'

services:
  mygitlab:
    # image: 'gitlab/gitlab-ce:latest'
    image: gitlab/gitlab-ce:12.9.2-ce.0
    container_name: mygitlab
    restart: always
    hostname: mygitlab.com
    ports:
      - 20080:80
      - 20022:22
      - 20443:443
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      - TZ=Asia/Taipei

volumes:
  gitlab-config: {}
  gitlab-logs: {}
  gitlab-data: {}
