version: "3.8"

services:
  zabbix_db:
    image: mysql:5.7
    container_name: zabbix_db
    hostname: db
    restart: always
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - ./mysql/conf.d/:/etc/mysql/conf.d/:rw
      - /etc/localtime:/etc/localtime:ro
      - zabbix_db:/var/lib/mysql
      - zabbix_db_log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      zabbix_net:
        # ipv4_address: 172.30.0.10
    stop_grace_period: 10s

  zabbix_server:
    image: zabbix_server:4.0.27
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: zabbix_server
    hostname: server
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server/zabbix:/etc/zabbix:rw
      - zabbix_server_log:/var/log/zabbix
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      MYSQL_DATABASE: ${DB_NAMW}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env_srv
    depends_on:
      - zabbix_db
    networks:
      zabbix_net:
        # ipv4_address: 172.30.0.20
    stop_grace_period: 5s
    # sysctls:
    #   - net.ipv4.ip_local_port_range=1024 65000
    #   - net.ipv4.conf.all.accept_redirects=0
    #   - net.ipv4.conf.all.secure_redirects=0
    #   - net.ipv4.conf.all.send_redirects=0
    labels:
      com.docker.version: "20.10.2"
      com.docker.compose.version: "1.28.2"
      author.email: "cool21540125@gmail.com"
      author.team: "delta-ops Taipei"

  zabbix_web:
    image: zabbix_web:4.0.27
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: zabbix_web
    hostname: web
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_TZ: ${PHP_TZ}
    networks:
      - zabbix_net
    depends_on: 
      - zabbix_server

networks:
  zabbix_net:
    name: zabbix_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  zabbix_server:
    name: zabbix_server
  zabbix_server_log:
    name: zabbix_server_log
  zabbix_db:
    name: zabbix_db
  zabbix_db_log:
    name: zabbix_db_log
