version: "3.8"

services:
  zabbix_db:
    image: mysql:5.7
    container_name: zabbix_db
    hostname: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/:/etc/mysql/conf.d:rw
      - /etc/localtime:/etc/localtime
      - zabbix_db:/var/lib/mysql
      - zabbix_db_log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      zabbix_net:
        # ipv4_address: 172.30.0.10
    stop_grace_period: 10s

  zabbix_server:
    image: zabbix_server:4.0.27
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: zabbix_server
    hostname: server
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/zabbix:/etc/zabbix:rw
      - zabbix_server_log:/var/log/zabbix
    environment:
      DB_SERVER_HOST: zabbix_db
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env_srv
    depends_on:
      - zabbix_db
    networks:
      zabbix_net:
        # ipv4_address: 172.30.0.20
    stop_grace_period: 5s
    # sysctls:
    #   - net.ipv4.ip_local_port_range=1024 65000
    #   - net.ipv4.conf.all.accept_redirects=0
    #   - net.ipv4.conf.all.secure_redirects=0
    #   - net.ipv4.conf.all.send_redirects=0
    labels:
      com.docker.version: "20.10.2"
      com.docker.compose.version: "1.28.2"
      author.email: "cool21540125@gmail.com"
      author.team: "delta-ops Taipei"

networks:
  zabbix_net:
    name: zabbix_net
    driver: bridge
    ipam: 
      config:
        - subnet: 172.30.0.0/16

volumes:
  zabbix_server:
    name: zabbix_server
  zabbix_server_log:
    name: zabbix_server_log
  zabbix_db:
    name: zabbix_db
  zabbix_db_log:
    name: zabbix_db_log
  zabbix_db_conf:
    name: zabbix_db_conf
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/conf.d/"