version: "3"

services:
  redis6:
    image: redis:6.0
    container_name: redis6
    hostname: redis6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data_redis:/data"
    networks:
      - net_redis

volumes:
  net_redis:
    name: net_redis