version: '3'

services:
  mysql57_data:
    image: mysql:5.7
    container_name: mysql57_data
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - mysql57_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
volumes:
  mysql57_data:
    name: mysql57_data