version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - net_kfk
  kafka:
    image: bitnami/kafka:2.8.1
    ports:
      - '9092:9092'
      - '9093:9093'
    env_file:
      - "kafka.env"
    depends_on:
      - zookeeper
    networks:
      - net_kfk

networks:
  net_kfk:
    name: net_kfk