version: "3"
services:
  prometheus:
    image:  prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime
      - vol_prometheus:/prometheus
    networks:
      - net_devops
    ports:
      - 9090:9090
    command: ["--config.file=/etc/prometheus/prometheus.yml"]

volumes:
  vol_prometheus:
    name: vol_prometheus

networks:
  net_devops:
    external: true
