version: "3"
services:
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.49.1"
    container_name: "cadvisor"
    hostname: "cadvisor"
    restart: "always"
    privileged: true
    ports:
      - "28080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      net_monitoring:
    devices:
      - "/dev/kmsg"

  prometheus:
    image: "prom/prometheus:v2.53.0" # Use LTS
    container_name: "prometheus"
    hostname: "prometheus"
    restart: "always"
    ports:
      - "29090:9090"
    volumes:
      - "./config/prometheus:/etc/prometheus"
      - "vol_prometheus:/prometheus"
      #- "/var/run/docker.sock:/var/run/docker.sock:rw" # 需要讓 prometheus container 的 user 可以對 docker.sock 做 rw !!!
    networks:
      net_monitoring:
    depends_on:
      - cadvisor
      - grafana
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.config.file=/etc/prometheus/web.yml",
        "--storage.tsdb.path=/prometheus",
        "--web.enable-lifecycle",
        "--web.console.libraries=/usr/share/prometheus/console_libraries",
        "--web.console.templates=/usr/share/prometheus/consoles",
      ]
    extra_hosts:
      - "docker_host:host-gateway" # node_exporter location

  alertmanager:
    image: "quay.io/prometheus/alertmanager:v0.27.0"
    container_name: "alertmanager"
    hostname: "alertmanager"
    restart: "always"
    ports:
      - "29093:9093"
    volumes:
      - "./config/alertmanager:/etc/alertmanager"
    networks:
      net_monitoring:
    depends_on:
      - prometheus
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]

  grafana:
    image: "grafana/grafana:11.1.0"
    container_name: "grafana"
    hostname: "grafana"
    restart: "always"
    ports:
      - "23000:3000"
    volumes:
      - "vol_grafana:/var/lib/grafana"
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/ldap.toml:/etc/grafana/ldap.toml"
    networks:
      net_monitoring:

volumes:
  vol_prometheus:
    name: vol_prometheus
  vol_grafana:
    name: vol_grafana

networks:
  net_monitoring:
    external: true
