version: "3"
services:
  cadvisor:
    container_name: "cadvisor"
    hostname: "cadvisor"
    privileged: true
    restart: "always"
    image: "gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION}"
    ports:
      - "28080:8080"
    volumes: 
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      net_monitoring:
    devices: 
      - "/dev/kmsg"

  prometheus:
    container_name: "prometheus"
    hostname: "prometheus"
    restart: "always"
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    ports:
      - "29090:9090"
    volumes:
      - "./config:/etc/prometheus"
      - "vol_prometheus:/prometheus"
    networks:
      net_monitoring:
    depends_on:
      - cadvisor
    command: [ "--config.file=/etc/prometheus/prometheus.yml",
               "--web.config.file=/etc/prometheus/web.yml",
               "--storage.tsdb.path=/prometheus",
               "--web.enable-lifecycle",
               "--web.console.libraries=/usr/share/prometheus/console_libraries",
               "--web.console.templates=/usr/share/prometheus/consoles" ]

  alertmanager:
    container_name: "alertmanager"
    hostname: "alertmanager"
    restart: "always"
    image: "quay.io/prometheus/alertmanager:${ALERTMANAGER_VERSION}"
    ports:
      - "29093:9093"
    volumes:
      - "./config:/etc/alertmanager"
    networks:
      net_monitoring:
    depends_on:
      - prometheus
    command: [ "--config.file=/etc/alertmanager/alertmanager.yml" ]

networks:
  net_monitoring:
    external: true

volumes:
  vol_prometheus:
    name: vol_prometheus
