version: "3"
services:
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.49.1"
    container_name: "cadvisor"
    hostname: "cadvisor"
    restart: "always"
    privileged: true
    ports:
      - "28080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      net_monitoring:
    devices:
      - "/dev/kmsg"

  prometheus:
    image: "prom/prometheus:v2.53.0" # Use LTS
    container_name: "prometheus"
    hostname: "prometheus"
    restart: "always"
    ports:
      - "29090:9090"
    volumes:
      - "./config:/etc/prometheus"
      - "vol_prometheus:/prometheus"
    networks:
      net_monitoring:
    depends_on:
      - cadvisor
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.config.file=/etc/prometheus/web.yml",
        "--storage.tsdb.path=/prometheus",
        "--web.enable-lifecycle",
        "--web.console.libraries=/usr/share/prometheus/console_libraries",
        "--web.console.templates=/usr/share/prometheus/consoles",
      ]
    extra_hosts:
      - "docker_host:192.168.200.1" # node_exporter location

  alertmanager:
    image: "quay.io/prometheus/alertmanager:v0.27.0"
    container_name: "alertmanager"
    hostname: "alertmanager"
    restart: "always"
    ports:
      - "29093:9093"
    volumes:
      - "./config:/etc/alertmanager"
    networks:
      net_monitoring:
    depends_on:
      - prometheus
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]

volumes:
  vol_prometheus:
    name: vol_prometheus

networks:
  net_monitoring:
    external: true
