
@url={{$dotenv DDOG_SITE}}
@DD_API_KEY={{$dotenv DD_API_KEY}}
@DD_APP_KEY={{$dotenv DD_APP_KEY}}

@metric_name={{$dotenv metric_name}}
@q={{$dotenv q}}



### Get all hosts for your organization
# https://docs.datadoghq.com/api/latest/hosts/#get-all-hosts-for-your-organization
GET {{url}}/api/v1/hosts
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}




### Get the total number of active hosts
# https://docs.datadoghq.com/api/latest/hosts/#get-the-total-number-of-active-hosts
GET {{url}}/api/v1/hosts/totals
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}
