
@url={{$dotenv DDOG_SITE}}
@DD_API_KEY={{$dotenv DD_API_KEY}}
@DD_APP_KEY={{$dotenv DD_APP_KEY}}

@metric_name={{$dotenv metric_name}}
@q={{$dotenv q}}


### Get active metrics list
@from=1669852800
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#get-active-metrics-list
GET {{url}}/api/v1/metrics?from={{from}}
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### Get a list of metrics
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#get-a-list-of-metrics
GET {{url}}/api/v2/metrics
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### Get metric metadata
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#get-metric-metadata
GET {{url}}/api/v1/metrics/{{metric_name}}
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}


### Submit distribution points
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#submit-distribution-points
# 具有破壞性!!!!!! 除非知道自己在幹嘛, 否則別用!!!!!!!!!!


### Query timeseries points - 還需要問 DDOG 官方, 這說明文件太弱了
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#query-timeseries-points
GET {{url}}/api/v1/query
  ?from={{$timestamp -8 h}}
  &to={{$timestamp}}
  &query={{metric_name}}
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### Search metrics
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#search-metrics
GET {{url}}/api/v1/search?q={{q}}
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### List active tags and aggregations
# https://docs.datadoghq.com/api/latest/metrics/?code-lang=curl#list-active-tags-and-aggregations
GET  {{url}}/api/v2/metrics/{{metric_name}}/active-configurations
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### 
