
@url={{$dotenv DDOG_SITE}}
@DD_API_KEY={{$dotenv DD_API_KEY}}
@DD_APP_KEY={{$dotenv DD_APP_KEY}}

@metric_name={{$dotenv metric_name}}


### Validate API key
# https://docs.datadoghq.com/api/latest/authentication/#validate-api-key
# 還蠻廢的 API.... 只是用來驗證 API Key 是否可用......
GET {{url}}/api/v1/validate
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}

