
@url={{$dotenv DDOG_SITE}}
@DD_API_KEY={{$dotenv DD_API_KEY}}
@DD_APP_KEY={{$dotenv DD_APP_KEY}}

@dashboard_id={{$dotenv dashboard_id}}



### Get all dashboard lists
# https://docs.datadoghq.com/api/latest/dashboard-lists/#get-all-dashboard-lists
# 不曉得為啥這支無法使用, 就不鳥他了


### Get all dashboards
# https://docs.datadoghq.com/api/latest/dashboards/#get-all-dashboards
GET {{url}}/api/v1/dashboard
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}




### Get a dashboard
# https://docs.datadoghq.com/api/latest/dashboards/#get-a-dashboard
GET {{url}}/api/v1/dashboard/{{dashboard_id}}
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### 
