
@url={{$dotenv DDOG_SITE}}
@DD_API_KEY={{$dotenv DD_API_KEY}}
@DD_APP_KEY={{$dotenv DD_APP_KEY}}

@incident_id={{$dotenv incident_id}}


### Get a list of incidents
# https://docs.datadoghq.com/api/latest/incidents/#get-a-list-of-incidents
GET {{url}}/api/v2/incidents/
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}



### Delete an existing incident
# https://docs.datadoghq.com/api/latest/incidents/#delete-an-existing-incident
DELETE {{url}}/api/v2/incidents/{{incident_id}}
DD-API-KEY: {{DD_API_KEY}}
DD-APPLICATION-KEY: {{DD_APP_KEY}}
