### Cloudflare API Documentation - https://api.cloudflare.com/#zone-settings-get-always-online-setting

@api=https://api.cloudflare.com/client/v4
@email={{cf_email}}
@token={{cf_key}}
@status = active

@domain={{$dotenv domain}}



# https://api.cloudflare.com/#zone-list-zones
### List Zones - 用域名查出對應的 zone_id (域名操作需要它)
# @name list_zones
GET {{api}}/zones
    ?name={{domain}}
    &page=1
    &per_page=50
    &order=status
    &direction=desc
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



### Zone ID
@zone_id = {{list_zones.response.body.result[0].id}}



# https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
### List DNS Records - 列出 特定域名 的所有解析紀錄
GET {{api}}/zones/{{zone_id}}/dns_records
    ?page=1
    &per_page=200
    &order=type
    &direction=desc
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#zone-settings-get-always-use-https-setting
### Get Always Use HTTPS setting - 強制使用 https
GET {{api}}/zones/{{zone_id}}/settings/always_use_https
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#zone-settings-change-always-use-https-setting
### Change Always Use HTTPS setting - 變更是否強制使用 https
PATCH {{api}}/zones/{{zone_id}}/settings/always_use_https
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json

{
    //"value": "off"
    "value": "on"
}



# https://api.cloudflare.com/#page-rules-for-a-zone-list-page-rules
### List Page Rules - 列出 Page Rules 清單
GET {{api}}/zones/{{zone_id}}/pagerules
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record
### Create DNS Record - 新增 特定域名(zone_id) 一筆解析紀錄
# @name new_record
POST {{api}}/zones/{{zone_id}}/dns_records
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json

{
    "type": "A",
    "name": "tony_demo",
    "content": "127.0.0.1",
    "ttl": "1"
}

### New_Record_ID
@new_record_id = {{new_record.response.body.result.id}}


@record_type=A
@recore_name=
@recore_value=
# https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record
### Update DNS Record - 修改 特定域名(zone_id) 的解析紀錄
PUT {{api}}/zones/{{zone_id}}/dns_records/{{new_record_id}}
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json

{
    "type": "{{record_type}}",
    "name": "{{recore_name}}",
    "content": "{{recore_value}}",
    "ttl": "1"
}



# https://api.cloudflare.com/#dns-records-for-a-zone-dns-record-details
### DNS Record Details - 查詢 特定域名(zone_id) 的解析紀錄
GET {{api}}/zones/{{zone_id}}/dns_records/{{new_record_id}}
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#dns-records-for-a-zone-delete-dns-record
### Delete DNS Record - 刪除 特定域名(zone_id) 的解析紀錄
DELETE {{api}}/zones/{{zone_id}}/dns_records/{{new_record_id}}
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#zone-purge-all-files
### Purge All Files - 清除 特定域名(zone_id) 的靜態資源快取
POST {{api}}/zones/{{zone_id}}/purge_cache
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json

{
    "purge_everything": true
}



# https://api.cloudflare.com/#zone-zone-details
### Zone Details - (通常用不到這個) 查詢 zone_id 的詳細記錄(與權限, 帳戶資訊較為相關)
GET {{api}}/zones/{{zone_id}}
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#zone-settings-get-ipv6-setting
### Get IPv6 setting - 查詢 域名的 IPv6 設定
GET {{api}}/zones/{{zone_id}}/settings/ipv6
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json



# https://api.cloudflare.com/#zone-settings-change-ipv6-setting
### Change IPv6 setting - 變更 IPv6 設定
PATCH {{api}}/zones/{{zone_id}}/settings/ipv6
X-Auth-Email: {{email}}
X-Auth-Key: {{token}}
Content-Type: application/json

{
    "value":"off"
}



#