version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - "./build:/build"
      # - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    networks:
      - net_nginx

networks:
  net_nginx:
    name: net_nginx