
services:
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.68.0
    container_name: jaeger
    hostname: jaeger
    restart: "always"
    ports:
      # - "4317:4317"      # gRPC OTLP
      # - "4318:4318"      # HTTP OTLP
      - "5775:5775/udp"  # UDP  zipkin.thrift compact
      - "5778:5778"      # HTTP Jaeger service
      - "6831:6831/udp"  # UDP  jaeger.thrift compact
      - "6832:6832/udp"  # UDP  jaeger.thrift binary
      - "9411:9411"      # HTTP zipkin
      # - "14250:14250"    # ?? model.proto
      - "14268:14268"    # HTTP Client 直接送 jaeger.thrift
      # - "14269:14269"    # ?? status??
      - "16686:16686"    # HTTP Jaeger WebUI (必要)
