
@token={{$dotenv token}}
@namespace={{$dotenv account}}


### List repository tags
# https://docs.docker.com/docker-hub/api/latest/#tag/repositories/paths/~1v2~1namespaces~1%7Bnamespace%7D~1repositories~1%7Brepository%7D~1tags/get
GET https://hub.docker.com/v2/namespaces/{{namespace}}/repositories/os7-tools/tags
Authorization: Bearer {{token}}


### 
