version: '3.9'

services:
  registry:
    image: registry:2.7.1
    container_name: registry
    hostname: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data_registry:/var/lib/registry"
    networks:
      - net_registry
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

networks:
  net_registry:
    name: net_registry