version: '3'

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`$WHOAMI_HOST`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      net_app:

networks:
  net_app:
    external: true
