global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: https://webhook.site/#!/view/086c1994-551d-41e1-a1a7-95de45af0f7e
          send_resolved: false