version: "3"

services:
  mysql57:
    image: mysql57
    build:
      context: .
    container_name: mysql57
    hostname: mysql57
    restart: always
    ports:
      - "3357:3306"
    volumes:
      - ./data_db:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - net_mysql57

networks:
  net_mysql57:
    name: net_mysql57