services:

  wordpress:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./logs:/var/log
    # healthcheck:


  db:
    image: mysql:8
    container_name: wordpress_db
    hostname: wordpress_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: python
    volumes:
      - wordpress_db_data:/var/lib/mysql

volumes:
  wordpress_data:
    name: wordpress_data

  wordpress_db_data:
    name: wordpress_db_data