global:
  scrape_interval: 20s
  scrape_timeout: 3s
  evaluation_interval: 20s
  # query_log_file: /var/log/prometheus/query.log  # 用來記錄所有的 prometheus query

rule_files:
  - rules_alert.yml
  - rules_record.yml

scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: "10s"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - regex: "container_label_(org|com).+"
        action: labeldrop
      - regex: "container_label_maintainer"
        action: labeldrop

  - job_name: "prometheus"
    basic_auth:
      username: "admin"
      password: "<明碼密碼>" # FIXME: bcrypt(<明碼密碼>) 需要放置於 web.yml
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["docker_host:9100"]
    #file_sd_configs:
    #  - files:
    #      - "node_targets.json"

  - job_name: "grafana"
    scrape_interval: "30s"
    static_configs:
      - targets: ["grafana:3000"]

  #- job_name: "docker"
  #  docker_sd_configs:
  #    - host: "unix:///var/run/docker.sock"
  #    - host: "DOCKER_HOST_IP_BUT_STILL_NOT_SUCCESS"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
