#!/bin/bash
#
# Copyright 2014 Red Hat, Inc.
#
# NAME
#     lab-dnsissue1 - setup script for RH254/RH299 DNS troubleshooting exercise
#
# SYNOPSIS
#     lab-dnsissue1 setup
#
#     This script only works on desktopX.example.com.
#
# DESCRIPTION
#     This script performs the setup for one of the DNS troubleshooting
#     practice exercises for RH254.
#
# CHANGELOG
#   * Tue May 27 2014 Chen Chang <cchang@redhat.com>
#   - original code

# Initialize and set some variables
MYHOST=""
CMD=""
DEBUG='true'
RUN_AS_ROOT='true'

# Source library of functions
source /usr/local/bin/labtool.shlib
trap on_exit EXIT

# Additional functions for this shell script
function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the setup and grading of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help
COMMAND is one of:
    setup - perform any setup steps for this lab on this machine
EOF
}

function lab_setup {
    VMNAME=$1
    case $VMNAME in
        desktop)
            echo '172.25.254.255 example.com' >> /etc/hosts

            if [ $? -ne 0 ]; then
              print_FAIL && echo "Failed populating /etc/hosts."
            fi
            ;;
        server)
            print_FAIL && echo "The setup script needs to be run on desktop"
            ;;
        *)
            print_FAIL && echo "The setup script needs to be run on desktop"
            ;;
    esac

}

# Main area

# Check if to be run as root (must do this first)
if [[ "${RUN_AS_ROOT}" == 'true' ]] && [[ "${EUID}" -gt "0" ]] ; then
  if [[ -x /usr/bin/sudo ]] ; then
    ${SUDO:-sudo} $0 "$@"
    exit
  else
    # Fail out if not running as root
    check_root
  fi
fi

# Process command line
# Parse input
case $1 in
    setup)
        CMD=$1
        ;;
    -h|--help)
        print_usage
        exit 0
        ;;
    *)
        echo Bad option $1
        print_usage
        exit 1
        ;;
esac
# Validation
[ -z "$CMD" ] && debug "Missing command" && print_usage && exit 1

# Get local system information
get_X

# Branch based on short (without number) hostname
case $MYHOST in
    desktop|server)
        lab_$CMD $MYHOST
        ;;
    *)
        debug "Bad or missing hostname - $MYHOST"
        debug "This command needs to be run on desktop or server"
        exit 3
        ;;
esac

