# 
@packageName={{$dotenv packageName}}
@editId={{$dotenv editId}}
@url=https://androidpublisher.googleapis.com
@client_id={{$dotenv client_id}}
@API_KEY={{$dotenv API_KEY}}
@token={{$dotenv token}}


### Methods: edits.bundles.list
# https://developers.google.com/android-publisher/api-ref/rest/v3/edits.bundles/list
GET {{url}}/androidpublisher/v3/applications/{{packageName}}/edits/{{editId}}/bundles
Authorization: Bearer {{token}}


### Method: reviews.list
# https://developers.google.com/android-publisher/api-ref/rest/v3/reviews/list
GET {{url}}/androidpublisher/v3/applications/{{packageName}}/reviews
Authorization: Bearer {{token}}


### Method: edits.details.get
# https://developers.google.com/android-publisher/api-ref/rest/v3/edits.details/get?hl=en
GET {{url}}/androidpublisher/v3/applications/{{packageName}}/edits/{{editId}}/details
Authorization: Bearer {{token}}


### 
