---
kind: pipeline
type: docker
name: Deploy Web

steps:
#  - name: build
#    image: node:latest
#    commands:
#      - npm install
#      - npm run-script build
  - name: Deploy
    image: appleboy/drone-scp
    settings:
      host: ${HOST=192.168.2.87}
      username: 
        from_secret: ${vm1_user}
      password: 
        from_secret: ${vm1_password}
      port: 22
      strip_components: 1
      source:
        - dist
      target:
        - /var/web

# drone exec --env-file ./secret
