@domain=127.0.0.1:5000
@url=http://{{domain}}

# ----------------------------------------------------
# Docker 官方 API
# https://docs.docker.com/registry/spec/api/#detail
# ----------------------------------------------------

### 查詢 Registry 有哪些 Images
GET {{url}}/v2/_catalog


### 查詢 特定 Image 有哪些 Tags
@image=alpine
GET {{url}}/v2/{{image}}/tags/list


@tag=latest
### 查詢 特定 Image 詳細資訊
GET {{url}}/v2/{{image}}/manifests/{{tag}}


### 移除 Tag