version: "3"

services:
  registry:
    image: registry:2.8
    container_name: registry
    hostname: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "vol_registry:/var/lib/registry"
    networks:
      - net_registry

networks:
  net_registry:
    name: net_registry

volumes:
  vol_registry:
    external: vol_registry
