# https://platform.openai.com/docs/api-reference/chat/create

@url=https://api.openai.com/v1/chat/completions
@token={{$dotenv SECRET_KEY}}


### 0~2: 越高越隨機, 越低越精確
@temperature=0.8


### 基本對話(需要把 timeout 調高...)
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "model": "gpt-3.5-turbo",
    "messages": [{ 
        "role": "user", 
        "content": "hi" 
    }],
    "temperature": {{temperature}}
}


### 
