# https://platform.openai.com/docs/api-reference/images/create

@url=https://api.openai.com/v1/images/generations
@token={{$dotenv SECRET_KEY}}


### 
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "prompt": "A girl looks like 'Annie Leonhart' in the anime: 'attack on titan'",
    "n": 1,
    "size": "1024x1024"
}


### 