
services:
  mysql8:
    image: mysql:8.4
    container_name: mysql84
    hostname: mysql84
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - vol_mysql84:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  vol_mysql84:
    name: vol_mysql84
    external: true