version: "3.7"

services:
  db:
    image: postgres:11
    container_name: mypg
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "4444:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  pg_data: