

@url=https://slack.com/api
@token={{$dotenv token}}
@channelID={{$dotenv channelID}}


### 
GET {{url}}/conversations.list
Authorization: Bearer {{token}}


### ----------------------------------
POST {{url}}/chat.postMessage
Authorization: Bearer {{token}}
Content-type: application/json

{
  "channel": "{{channelID}}",
  "text": "(({{$localDatetime 'MM/DD HH:mm:ss'}})) TEST123: {{$timestamp}} ~ {{$timestamp 5 s}}"
}


### ----------------------------------
# https://api.slack.com/messaging/scheduling
# BUG: post_at 如果在 10 秒內很容易出現 time_in_past (原因不明), 但偶爾能成功
@preparePostTS={{$timestamp 10 s}}
@preparePostTime={{$localDatetime 'MM/DD HH:mm:ss' 10 s}}
POST {{url}}/chat.scheduleMessage
Authorization: Bearer {{token}}
Content-type: application/json

{
  "channel": "{{channelID}}",
  "text": "(({{$localDatetime 'MM/DD HH:mm:ss'}} 發送10)) 預計 {{preparePostTime}} 送達",
  "post_at": {{preparePostTS}}
}





### 
GET {{url}}/conversations.list
Authorization: Bearer {{token}}