
# https://api.slack.com/methods
@url=https://slack.com/api
@channelID={{$dotenv channelID}}
@token={{$dotenv token}}
# -------------------------------------


### 取得 channel list
# https://api.slack.com/methods/conversations.list
GET {{url}}/conversations.list
Authorization: Bearer {{token}}



### 發送 即時訊息 -> 特定 channel
# https://api.slack.com/methods/chat.postMessage
POST {{url}}/chat.postMessage
Authorization: Bearer {{token}}
Content-type: application/json

{
  "channel": "{{channelID}}",
  "text": "{{$localDatetime 'MM/DD HH:mm:ss'}} @@@@ 即時訊息 @@@@\n目前 ts={{$timestamp}}"
}



### 發送 排程訊息 -> 特定 channel
# https://api.slack.com/methods/chat.scheduleMessage
@preparePostTS={{$timestamp 11 s}}
POST {{url}}/chat.scheduleMessage
Authorization: Bearer {{token}}
Content-type: application/json

{
  "channel": "{{channelID}}",
  "text": "{{$localDatetime 'MM/DD HH:mm:ss'}} @@@@ 排程訊息 @@@@\n預計 ts={{preparePostTS}} User 才會接收到",
  "post_at": {{preparePostTS}}
}
// NOTE: post_at 如果在 10 秒內很容易出現 time_in_past (原因不明), 但偶爾能成功



### 查看 TOKEN 基本資訊 - Checks authentication & identity.
# https://api.slack.com/methods/auth.test
POST {{url}}/auth.test
Authorization: Bearer {{token}}
Content-type: application/json



### 