version: "3"

services:
  flask:
    image: simple-flask-app
    container_name: flask
    networks:
      - net_app
    labels:
      - traefik.enable=true
      - traefik.http.routers.flask.rule=Host(`$APP_DOMAIN`)
      - traefik.http.routers.flask.entrypoints=web
      - traefik.http.services.flask.loadbalancer.server.port=5000

networks:
  net_app:
    external: true
