version: "3.8"

services:
  mongo:
    image: mongo44-bionic
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo
    hostname: ${HOSTNAME}
    restart: always
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_TOKEN=${APP_TOKEN}
      - APP_USER=${APP_USER}
      - APP_PASSWD=${APP_PASSWD}
    volumes:
      - "data_db:/data/db"
      - "data_configdb:/data/configdb"
      - "$PWD/mongod.conf:/etc/mongod.conf"
    networks:
      - net_mongo
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    command: ["mongod", "--config", "/etc/mongod.conf"]

networks:
  net_mongo:
    name: net_mongo
    driver: bridge

volumes:
  data_db:
    name: mongo_data
  data_configdb:
    name: mongo_sharding_configdb
