@URL=https://{{$dotenv DOMAIN}}
@CHANNEL_SECRET={{$dotenv CHANNEL_SECRET}}
@CHANNEL_ACCESS_TOKEN={{$dotenv CHANNEL_ACCESS_TOKEN}}
@RECV_CHANNEL_ID={{$dotenv RECV_CHANNEL_ID0}}
@ReplyToken={{$dotenv ReplyToken}}


### Send push message - 傳給單一頻道(可以是 user/group/chat)
# https://developers.line.biz/en/reference/messaging-api/#send-push-message
POST https://api.line.me/v2/bot/message/push
Content-Type: application/json
Authorization: Bearer {{CHANNEL_ACCESS_TOKEN}}

{
    "to": "{{RECV_CHANNEL_ID}}",
    "messages":[
        {
            "type":"text",
            "text":"私訊~ 私訊~ 現在時間 {{$localDatetime iso8601}}"
        }
    ]
}



### Send multicast message - 傳給多個 user/group/chat
# https://developers.line.biz/en/reference/messaging-api/#send-multicast-message
POST https://api.line.me/v2/bot/message/multicast
Content-Type: application/json
Authorization: Bearer {{CHANNEL_ACCESS_TOKEN}}

{
    "to": ["{{RECV_CHANNEL_ID1}}"],
    "messages":[
        {
            "type":"text",
            "text":"群播~ 群播~ 現在時間 {{$localDatetime iso8601}}"
        }
    ]
}



### Send broadcast message - 廣播給 所有個人 user(非 group/chat)
# https://developers.line.biz/en/reference/messaging-api/#send-broadcast-message
POST https://api.line.me/v2/bot/message/broadcast
Content-Type: application/json
Authorization: Bearer {{CHANNEL_ACCESS_TOKEN}}

{
    "messages": [
        {
            "type": "text",
            "text": "廣播! 廣播! 現在時間 {{$localDatetime iso8601}}"
        }
    ]
}



### Send narrowcast message - 依照 用戶屬性 來做特定族群廣播
# https://developers.line.biz/en/reference/messaging-api/#send-narrowcast-message
# pass



### Send reply message - 針對訊息做回應 (需要有 Webhook Server 取得 ReplyToken)
# https://developers.line.biz/en/reference/messaging-api/#send-reply-message
POST https://api.line.me/v2/bot/message/reply
Content-Type: application/json
Authorization: Bearer {{CHANNEL_ACCESS_TOKEN}}

{
    "replyToken":"{{ReplyToken}}",
    "messages":[
        {
            "type":"text",
            "text":"Hello, user"
        }
    ]
}



### Get number of messages sent this month - 這個月對做了幾次訊息推送
# https://developers.line.biz/en/reference/messaging-api/#get-consumption
GET https://api.line.me/v2/bot/message/quota/consumption
Content-Type: application/json
Authorization: Bearer {{CHANNEL_ACCESS_TOKEN}}



### 
# https://developers.line.biz/en/reference/messaging-api/#video-message
POST https://api.line.me/v2/bot/message/push
Content-Type: application/json
Authorization: Bearer {{CHANNEL_ACCESS_TOKEN}}

{
    "to": "{{RECV_CHANNEL_ID1}}",
    "messages": [
        {
            "type": "text",
            "text": "小霏會站了, 而且還會扭屁股噢"
        },
        {
            "type": "video",
            "originalContentUrl": "https://linebottf.s3-ap-northeast-1.amazonaws.com/linebot/dance.mp4",
            "previewImageUrl": "https://linebottf.s3-ap-northeast-1.amazonaws.com/linebot/dance.png"
        }
    ]
}



### 
#