version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts-centos7
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
    - "jenkins_home:/var/jenkins_home"
    - "/etc/localtime:/etc/localtime:ro"

volumes:
  jenkins_home:
    name: jenkins_home