<<<<<<< HEAD
# 2021/01/02 - 2.263
version: "3"
services:
  jenkins:
    image: docker pull jenkins/jenkins:2.263.1-lts-centos7
    container_name: myjenkins
    restart: always
    ports:
      - "8080:8080"
=======
version: "3"
services:
  jenkins:
    image: jenkins/jenkins:2.263.1-lts-centos7
    container_name: my_jenkins
    restart: always
    ports:
      - "8089:8080"
>>>>>>> 7e5e242ebecce34e956d236898144ae3d94fa5de
      - "50000:50000"
    volumes:
    - jenkins_data:/var/jenkins_home
volumes:
  jenkins_data:
<<<<<<< HEAD
=======
    name: jenkins_data
>>>>>>> 7e5e242ebecce34e956d236898144ae3d94fa5de
