version: "3.8"

services:
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:centos-4.0.27
    container_name: zabbix_web
    hostname: zabbix_web
    restart: always
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_SERVER_PORT: ${ZBX_SERVER_PORT}
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
      PHP_TZ: "Asia/Taipei"
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - zabbix_service

networks:
  zabbix_service:
    name: zabbix_service
    driver: bridge