name: 3100_loki

services:

  carnivorous-garden:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5005:5000
    volumes:
      - ./logs:/app/logs/

  alloy:
    image: grafana/alloy:latest
    ports:
      - 12345:12345
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - ./logs:/tmp/app-logs/
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - carnivorous-garden
      - loki

  loki:
    image: grafana/loki:main-e9b6ce9
    ports:
      - "3100:3100"
    volumes:
      - "example_loki/loki-config.yaml:/etc/loki/local-config.yaml"
      # - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:11.0.0
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana:/etc/grafana/provisioning

