version: "3.8"

services:
  redis01:
    image: redis:6.0
    container_name: redis6001
    hostname: redis6001
    restart: always
    ports:
      - "6001:6001"
      - "16001:16001"
    volumes:
      - "data_6001:/data/"
      - "./6001/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      - net_rediscluster
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis02:
    image: redis:6.0
    container_name: redis6002
    hostname: redis6002
    restart: always
    ports:
      - "6002:6002"
      - "16002:16002"
    volumes:
      - "data_6002:/data/"
      - "./6002/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      - net_rediscluster
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis03:
    image: redis:6.0
    container_name: redis6003
    hostname: redis6003
    restart: always
    ports:
      - "6003:6003"
      - "16003:16003"
    volumes:
      - "data_6003:/data/"
      - "./6003/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      - net_rediscluster
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis04:
    image: redis:6.0
    container_name: redis6004
    hostname: redis6004
    restart: always
    ports:
      - "6004:6004"
      - "16004:16004"
    volumes:
      - "data_6004:/data/"
      - "./6004/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      - net_rediscluster
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis05:
    image: redis:6.0
    container_name: redis6005
    hostname: redis6005
    restart: always
    ports:
      - "6005:6005"
      - "16005:16005"
    volumes:
      - "data_6005:/data/"
      - "./6005/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      - net_rediscluster
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis06:
    image: redis:6.0
    container_name: redis6006
    hostname: redis6006
    restart: always
    ports:
      - "6006:6006"
      - "16006:16006"
    volumes:
      - "data_6006:/data/"
      - "./6006/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      - net_rediscluster
    command: ["redis-server", "/etc/redis/redis.conf"]

networks:
  net_rediscluster:
    driver: bridge

volumes:
  data_6001:
    external: true
  data_6002:
    external: true
  data_6003:
    external: true
  data_6004:
    external: true
  data_6005:
    external: true
  data_6006:
    external: true