version: "3"

services:
  redis01:
    image: redis:6
    container_name: redis01
    hostname: redis01
    restart: always
    ports:
      - "6001:6001"
      - "16001:16001"
    volumes:
      - "vol_redis01:/data/"
      - "./01/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      net_rediscluster:
        ipv4_address: 172.72.72.61
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis02:
    image: redis:6
    container_name: redis02
    hostname: redis02
    restart: always
    ports:
      - "6002:6002"
      - "16002:16002"
    volumes:
      - "vol_redis02:/data/"
      - "./02/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      net_rediscluster:
        ipv4_address: 
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis03:
    image: redis:6
    container_name: redis03
    hostname: redis03
    restart: always
    ports:
      - "6003:6003"
      - "16003:16003"
    volumes:
      - "vol_redis03:/data/"
      - "./03/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      net_rediscluster:
        ipv4_address: 172.72.72.63
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis04:
    image: redis:6
    container_name: redis04
    hostname: redis04
    restart: always
    ports:
      - "6004:6004"
      - "16004:16004"
    volumes:
      - "vol_redis04:/data/"
      - "./04/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      net_rediscluster:
        ipv4_address: 172.72.72.64
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis05:
    image: redis:6
    container_name: redis05
    hostname: redis05
    restart: always
    ports:
      - "6005:6005"
      - "16005:16005"
    volumes:
      - "vol_redis05:/data/"
      - "./05/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      net_rediscluster:
        ipv4_address: 172.72.72.65
    command: ["redis-server", "/etc/redis/redis.conf"]
  redis06:
    image: redis:6
    container_name: redis06
    hostname: redis06
    restart: always
    ports:
      - "6006:6006"
      - "16006:16006"
    volumes:
      - "vol_redis06:/data/"
      - "./06/:/etc/redis/"
    environment: 
      REDISCLI_AUTH: ${REDISCLI_AUTH}
    networks:
      net_rediscluster:
        ipv4_address: 172.72.72.66
    command: ["redis-server", "/etc/redis/redis.conf"]

networks:
  net_rediscluster:
    external: true

volumes:
  vol_redis01:
    name: vol_redis01
  vol_redis02:
    name: vol_redis02
  vol_redis03:
    name: vol_redis03
  vol_redis04:
    name: vol_redis04
  vol_redis05:
    name: vol_redis05
  vol_redis06:
    name: vol_redis06
