@URL=https://api.namecheap.com/xml.response
@api_key={{namecheap_api_key}}
@username={{namecheap_username}}
@client_ip=


# Domain 的 NS 要切換到哪台上面(逗號分隔)
@nameserver={{$dotenv ns}}
#※ ↓↓↓↓↓↓↓↓↓↓ ex: example.com, 要拆成 TLD=com & SLD=domain
@SLD=domain
@TLD=com
#※ ↑↑↑↑↑↑↑↑↑↑ ex: example.com, 要拆成 TLD=com & SLD=domain

### 將 NameCheap 帳戶的 NameServer 解析, 調整成 Cloudflare, 移轉至 {{client_ip}}
### https://www.namecheap.com/support/api/methods/domains-dns/set-custom/
POST {{URL}} HTTP/1.1
Content-Type: application/json

{
    "ApiUser": "{{username}}",
    "ApiKey": "{{api_key}}",
    "UserName": "{{username}}",
    "Command": "namecheap.domains.dns.setCustom",
    "ClientIp": "{{client_ip}}",
    "SLD": "{{SLD}}",
    "TLD": "{{TLD}}",
    "NameServers": "{{nameserver}}"
}
