# 這一份只是用來做筆記 (不要直接複製貼上來使用)

global:
  scrape_interval: 15s
  scrape_timeout: 3s
  evaluation_interval: 1m # prometheus 每隔多久會對 rule_files 做一次 evaluate
  # external_labels:
  #   - name: value

  # query_log_file: /var/log/prometheus/query.log  # 用來記錄所有的 prometheus query

scrape_configs:
  - job_name: "cadvisor"  # 預設的 target job 的標籤名稱
    scrape_interval: "10s"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - regex: "container_label_(org|com).+"
        action: labeldrop
      - regex: "container_label_maintainer"
        action: labeldrop

  - job_name: "EC2-TkoMongoDB__prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # 此欄位會是 __address__

  - job_name: "EC2_TkoMongoDB__node_exporter"
    static_configs:
      - targets: ["docker_host:9100"]
