# ansible-playbook THIS_YAML                      # use default
# ansible-playbook THIS_YAML -e "demo_name=Tony2" # overwrite
- name: demo template
  hosts: localhost
  vars:
    demo_name: "Tony"
  
  tasks:
    - name: generation the demo.txt file
      template:
        src: demo_template.j2
        dest: /tmp/demo.txt
    
    - name: show
      command: cat /tmp/demo.txt
      register: result

    - name: print
      debug:
        msg: "{{ result.stdout_lines }}"