---
- name: Install vim
  hosts: localhost
  become: true
  tasks:
    # 在各種 distribution 安裝各自 packages
    - name: install vim in Ubuntu
      apt: 
        name: vim
        state: present
      when: ansible_pkg_mgr == "apt"
    - name: install vim in Centos
      yum: 
        name: vim 
        state: present
      when: ansible_pkg_mgr == "yum"
    