# ansible-playbook test_ansible_playbook.yaml
# 依照條件安裝套件+使用變數
---
- name: ec2 install pkgs
  hosts: ec2
  vars:
    packages:
      - name: mysql
        required: True
      - name: httpd
        required: True
  tasks:
    - name: Install {{ item.name }} on host
      yum:
        name: "{{ item.name }}"
        state: present
      become: true
      loop: "{{ packages }}"
      when: item.required == True
    
    # (底下還不確定沒用過, 但忘了哪邊看來的了)
    - name: xxx
      import_tasks: abc.yml
      when: ooo