version: "3.8"

services:
  gitea:
    image: gitea/gitea:1.14.2
    container_name: gitea
    restart: always
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__server__DOMAIN=${GITEA__server__DOMAIN}
      - GITEA__server__SSH_DOMAIN=${GITEA__server__SSH_DOMAIN}
      - GITEA__server__ROOT_URL=${GITEA__server__ROOT_URL}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea_db:3306
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__log__LEVEL=${LOG_LEVEL}
    networks:
      net_gitea:
    volumes:
      - "./data_gitea:/data"
      - "/home/git/.ssh/:/data/git/.ssh"
      - "/etc/localtime:/etc/localtime:ro"
      - "./app.ini:/data/gitea/conf/app.ini"
    ports:
      - "127.0.0.1:3080:3000"
      - "127.0.0.1:3222:22"
    depends_on:
      - gitea_db


  gitea_db:
    image: mysql:5.7
    container_name: gitea_mysql
    hostname: gitea_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    networks:
      net_gitea:
    volumes:
      - "./data_gitea_db:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

networks:
  net_gitea:
    name: net_gitea