version: "3.8"

services:
  gitea:
    image: gitea/gitea:1.13
    container_name: gitea
    restart: always
    networks:
      - gitea_net
      - bridge
    volumes:
      - "gitea_data:/data"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gitea_db
    hostname: gitea_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - gitea_net
    volumes:
      - "gitea_db:/var/lib/mysql"

networks:
  gitea_net:
    name: net_gitea

volumes:
  gitea_data:
    name: gitea_data
  gitea_db:
    name: gitea_db