
services:
  mongo:
    image: mongo:7
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "${PWD}/data_db:/data/db"
      - "${PWD}/sharding_config:/data/configdb"
      # - "${PWD}/mongod.conf:/etc/mongod.conf"
    networks:
      - net_mongo
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

networks:
  net_mongo:
    name: net_db
