version: "3"

services:
  mysql56:
    image: mysql56
    build:
      context: .
    container_name: mysql56
    hostname: mysql56
    restart: always
    ports:
      - "3356:3306"
    volumes:
      - ./data_db:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - net_mysql56

networks:
  net_mysql56:
    name: net_mysql56