version: '3'
services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    container_name: pypi
    restart: always
    ports:
      - "28888:8080"
    add:
      - ""
    volumes:
      - "./data/:/data/"
      - "pypiserver:/data/packages"
    entrypoint: ["-P", "htpasswd", "packages"]

volumes:
  pypiserver: