version: '3'
services:
  pypi:
    image: pypiserver/pypiserver:latest
    container_name: pypi
    restart: always
    ports:
      - "28888:8080"
    volumes:
      - "./auth:/auth"
      - "pypiserver:/data/packages"
    entrypoint: ["pypi-server", "-P", "/auth/pypi.htpasswd"]
    command: ["/data/packages"]

volumes:
 pypiserver: {}
