version: '3'
services:
  pypi:
    image: pypiserver/pypiserver:latest
    container_name: pypi
    restart: always
    ports:
      - "55555:8080"
    volumes:
      - "./auth:/data"
      - "./packages:/data/packages"
    # entrypoint: ["pypi-server", "-P", "/auth/pypi.htpasswd", "/data/packages"]
    entrypoint: ["pypi-server", "-P", "./data/pypi.htpasswd", "/data/packages"]

volumes:
  pypiserver: {}
