version: '3'
services:
  pypi:
    image: pypiserver/pypiserver:latest
    container_name: pypi
    restart: always
    ports:
      - "55555:8080"
    volumes:
      - "./auth:/data"
      - "pypiserver:/data/packages"
    entrypoint: ["pypi-server", "-P", "/data/pypi.htpasswd", "./packages"]

volumes:
  pypiserver: {}
