# https://docs.gitea.io/en-us/install-with-docker/
version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.11
    container_name: mygitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - mygitea:/data
    #   - /etc/timezone:/etc/timezone:ro
    #   - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

volumes:
  mygitea: {}
