version: "3"

services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Etc/UTC
      - TZ=Asia/Taipei
      - PUBLIC_KEY=$PUBLIC_KEY
      # - PUBLIC_KEY_DIR=/config
      # - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      # - USER_PASSWORD=password
      # - USER_PASSWORD_FILE=/path/to/file
      - USER_NAME=DevOps
    volumes:
      - "./config:/config"
    ports:
      - 2222:2222
    restart: unless-stopped
    networks:
      net_devops:

networks:
  net_devops:
    external: true
