
@TOKEN={{$dotenv VERCEL_TOKEN}}
@URL=https://api.vercel.com
@ProjectId={{$dotenv VERCEL_PROJECT_ID}}
@TeamId={{$dotenv VERCEL_TEAM_ID}}

# https://vercel.com/docs/rest-api/endpoints#webhooks




### List Webhooks
# https://vercel.com/docs/rest-api/endpoints#get-a-list-of-webhooks
# @name WebhookList
GET {{URL}}/v1/webhooks?teamId={{TeamId}}
Authorization: Bearer {{TOKEN}}



### 
