
@TOKEN={{$dotenv VERCEL_TOKEN}}
@URL=https://api.vercel.com
@ProjectId={{$dotenv VERCEL_PROJECT_ID}}
@TeamId=

# -------------------------------------------------------------------------
# https://vercel.com/docs/rest-api/endpoints#projects


### List secrets
# https://vercel.com/docs/rest-api/endpoints#list-secrets
# @name ProjectList
GET {{URL}}/v3/secrets
Authorization: Bearer {{TOKEN}}



### Create Secret
# https://vercel.com/docs/rest-api/endpoints#create-a-new-secret
POST {{URL}}/v2/secrets/name
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name": "secret-key-name",
    "value": "some secret value",
    "decryptable": true,
    "projectId": "{{ProjectId}}"
}


### Get Secret
GET {{URL}}/v3/secrets/secret-key-name
Authorization: Bearer {{TOKEN}}



### Modify Secret
# 略



### Delete Secret
DELETE {{URL}}/v2/secrets/my-api-key
Authorization: Bearer {{TOKEN}}



### 
