
@TOKEN={{$dotenv VERCEL_TOKEN}}
@URL=https://api.vercel.com
# @ProjectId={{$dotenv VERCEL_PROJECT_ID}}
@TeamId={{$dotenv VERCEL_TEAM_ID}}

# -------------------------------------------------------------------------
# https://vercel.com/docs/rest-api/endpoints#projects


### Retrieve a list of projects
# https://vercel.com/docs/rest-api/endpoints#retrieve-a-list-of-projects
# @name ProjectList
GET {{URL}}/v9/projects?teamId={{TeamId}}
Authorization: Bearer {{TOKEN}}



#
@ProjectId={{ProjectList.response.body.projects[0].id}}
@ProjectName={{ProjectList.response.body.projects[0].name}}
#



### Find a project
# https://vercel.com/docs/rest-api/endpoints#find-a-project-by-id-or-name
GET {{URL}}/v9/projects/{{ProjectId}}
Authorization: Bearer {{TOKEN}}



### Retrieve project domains
# https://vercel.com/docs/rest-api/endpoints#retrieve-project-domains-by-project-by-id-or-name
GET {{URL}}/v9/projects/{{ProjectId}}/domains
Authorization: Bearer {{TOKEN}}



### List env variables of a Project
# @name EnvironmentVariableList
# https://vercel.com/docs/rest-api/endpoints#retrieve-the-environment-variables-of-a-project-by-id-or-name
GET {{URL}}/v9/projects/{{ProjectId}}/env/
Authorization: Bearer {{TOKEN}}



# 
@EnvId={{EnvironmentVariableList.response.body.envs[0].id}}
# 



### Get environment variable (decrypted value)
# https://vercel.com/docs/rest-api/endpoints#retrieve-the-decrypted-value-of-an-environment-variable-of-a-project-by-id
GET {{URL}}/v9/projects/{{ProjectId}}/env/{{EnvId}}
Authorization: Bearer {{TOKEN}}



### Update the data cache feature
# https://vercel.com/docs/rest-api/endpoints#update-the-data-cache-feature
PATCH {{URL}}/v1/data-cache/projects/{{ProjectId}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    //"disabled": true
    "disabled": false
}



### 
