# Reference:
#     https://www.jenkins.io/doc/book/using/remote-access-api/
# ---------------------------------------------------
@HOST={{$dotenv JENKINS_HOST}}
@TOKEN={{$dotenv JENKINS_TOKEN}}
@USER={{$dotenv USER}}
@PASS={{$dotenv PASS}}

# @URL=http://{{USER}}:{{TOKEN}}@{{HOST}}
@URL=http://{{USER}}:{{PASS}}@{{HOST}}
@job_name={{$dotenv job_name}}
@tag={{$dotenv tag}}



### 列出 Jenkins Server 所有的 JenkinsJobs
GET {{URL}}/api/json?tree=jobs[fullName,displayName,url]



### 取得 特定JenkinsJob 的 Builds History
GET {{URL}}/job/{{job_name}}/api/json
    ?tree=builds[number,id,timestamp,result,duration]



### Jenkins 節點資訊, 可看到每個 JenkinsJob 最後一次的建置狀態
GET {{URL}}/api/json?pretty=true



### Trigger build
POST {{URL}}/job/{{job_name}}/buildWithParameters
    ?TAG={{tag}}



### 