apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol01
spec:
  accessModes:
    # - ReadOnlyMany
    - ReadWriteOnce
    # - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/data