# https://developers.google.com/chat/api/reference/rest/v1/cards#Card
# Built-In icons: https://developers.google.com/chat/api/guides/message-formats/cards#builtinicons

@spaceId={{$dotenv spaceId}}
@key={{$dotenv key}}
@token={{$dotenv token}}

@url=https://chat.googleapis.com/v1/spaces/{{spaceId}}/messages
# --------------------------------------------------------------


### Send Card
POST {{url}}?key={{key}}&token={{token}}
Content-Type: application/json

{
  "name": "myName",
  "text": "",
  "cardsV2": [
    {
      "cardId": "unique-card-id",
      "card": {
        "header": {
          "title": "Repo Name",
          "subtitle": "Repo Group Path",
          "imageUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png",
          "imageType": "SQUARE",
          "imageAltText": "Avatar for aaa"
        },
        "sections": [
          {
            "header": "Branch: feature",
            "collapsible": false,
            "uncollapsibleWidgetsCount": 1,
            "widgets": [
              {
                "decoratedText": {
                  "topLabel": "DATE: {{$localDatetime iso8601}}"
                }
              },
              {
                "decoratedText": {
                  "topLabel": "TYPE: commit"
                }
              },
              {
                "decoratedText": {
                  "topLabel": "MESSAGE: feat: [Fix] SocketIO"
                }
              },
              {
                "decoratedText": {
                  "topLabel": "AUTHOR: 大Boss"
                }
              },
              {
                "buttonList": {
                  "buttons": [
                    {
                      "text": "Share",
                      "onClick": {
                        "openLink": {
                          "url": "https://example.com/share"
                        }
                      }
                    },
                    {
                      "text": "Edit",
                      "onClick": {
                        "action": {
                          "function": "goToView",
                          "parameters": [
                            {
                              "key": "viewType",
                              "value": "EDIT"
                            }
                          ]
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        ]
      }
    }
  ]
}