version: '3'

services:
  dynamodb70:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb70
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "vol_dynamodb:/home/dynamodblocal/data"
    networks:
      - "net_dynamodb"

volumes:
  vol_dynamodb:
    external: true

networks:
  net_dynamodb:
    external: true
