services:
  ddb:
    image: "amazon/dynamodb-local:2.5.4"
    container_name: ddb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "vol_dynamodb:/home/dynamodblocal/data"
    networks:
      - "net_db"

volumes:
  vol_dynamodb:
    external: true

networks:
  net_db:
    external: true
