version: "3"

services:
  zabbix_web:
    # image: zabbix/zabbix-web-nginx-mysql:centos-4.0.27
    image: web
    # image: zabbix_web:4.0.27
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    hostname: web
    restart: always
    ports:
      - "8080:8080"
      - "80:80"
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_TZ: ${PHP_TZ}
    networks:
      - zabbix_net

networks:
  zabbix_net:
    name: zabbix_net
    driver: bridge

volumes:
  zabbix_web_log:
    name: zabbix_web_log