kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:  # 1 使用這個的話
    path: "/opt/local"
  nodeAffinity:  # 2 一定得用這個來宣告永存目錄
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - m1  # 3 以及指定機器
# 只要是 Local Volume 一定要透過 Persistent Volume 定義檔來使用
# 定義檔裏頭一定得宣告 nodeAffinity