apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:  # 用來針對 Pod 做資源限制
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    max:
      memory: 2Gi
    min:
      memory: 256Mi
    type: Container
