services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    hostname: mysql8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - vol_mysql8:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - net_mysql

networks:
  net_mysql:
    name: net_mysql

volumes:
  vol_mysql8:
    name: vol_mysql8
    external: true
