version: "3"

services:
  mysql8:
    image: mysql:8.0.22
    container_name: mysql8
    hostname: mysql8
    restart: always
    ports:
      - "3380:3306"
    volumes:
      - ./data_db:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - net_mysql80

networks:
  net_mysql80:
    name: net_mysql80