version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    restart: always
    networks:
      net_devops:
    ports:
      - "8080:8080"
      - "50000:50000"
    tty: true
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "dind-bin:/usr/local/dindbin"
    environment:
      - "DOCKER_HOST=tcp://dind:2376"
      - "DOCKER_CERT_PATH=/certs/client"
      - "DOCKER_TLS_VERIFY=1"
      - "PATH=/usr/local/dindbin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  dind:
    image: docker:dind
    container_name: dind
    hostname: dind
    restart: always
    privileged: true
    networks:
      net_devops:
    tty: true
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-docker-root:/var/lib/docker"
      - "dind-bin:/usr/local/bin"
    environment:
      - DOCKER_TLS_CERTDIR=/certs

volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs
  jenkins-docker-root:
    name: jenkins-docker-root
  dind-bin:
    name: dind-bin

networks:
  net_devops:
    name: net_devops
    external: true
