version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    restart: always
    networks:
      net_jenkins:
    ports:
      - "8080:8080"
      - "50000:50000"
    tty: true
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
  dind:
    image: docker:dind
    container_name: dind
    hostname: dind
    restart: always
    privileged: true
    networks:
      net_jenkins:
    tty: true
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-docker-root:/var/lib/docker"
    environment:
      - DOCKER_TLS_CERTDIR=/certs

volumes:
  jenkins-data:
    name: jenkins-data
    external: true
  jenkins-docker-certs:
    name: jenkins-docker-certs
    external: true
  jenkins-docker-root:
    name: jenkins-docker-root
    external: true

networks:
  net_jenkins:
    name: net_jenkins
