version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    restart: always
    networks:
      net_jenkins:
    ports:
      - "8080:8080"
      - "50000:50000"
    tty: true
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "jenkins_docker_certs:/certs/client:ro"
      - "$HOME:/home"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
  dind:
    image: docker:dind
    container_name: jenkins-dind
    hostname: jenkinsDinD
    restart: always
    privileged: true
    networks:
      net_jenkins:
    ports:
      - "2376:2376"
    tty: true
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "jenkins_docker_certs:/certs/client"
      - "$HOME:/home"
      - "jenkins_docker_root:/var/lib/docker"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  jenkins_data:
    name: jenkins_data
  jenkins_docker_certs:
    name: jenkins_docker_certs
  jenkins_docker_root:
    name: jenkins_docker_root

networks:
  net_jenkins:
    name: net_jenkins