version: "3"
services:
  redis:
    restart: always
    container_name: myredis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - "redis_data:/data"
      #- "./redis.conf:/usr/local/etc/redis/redis.conf"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.30'
    #       memory: 80M
    #     reservations:
    #       cpus: '0.10'
    #       memory: 50M
    command: redis-server
volumes:
  redis_data: {}