services:
  neo4j:
    image: neo4j:5.26.4-enterprise-ubi9
    container_name: neo4j
    hostname: neo4j
    restart: always
    ports:
      - "7688:7687"
      - "7475:7474"
    volumes:
      - vol_neo4j:/data
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    networks:
      - net_db

networks:
  net_db:
    external: true

volumes:
  vol_neo4j:
    external: true