services:
  neo4j:
    image: neo4j:5.24-community
    container_name: neo4j
    hostname: neo4j
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - vol_neo4j:/data
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    networks:
      - net_db

networks:
  net_db:
    external: true

volumes:
  vol_neo4j:
    external: true