# https://docs.gitlab.com/ee/api/jobs.html

@project_id={{$dotenv project_id}}



### List project jobs
# https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs
GET {{Gitlab_api_v4}}/projects/{{project_id}}/jobs
    ?order_by=updated_at
    &sort=desc
    &updated_after=2022-12-19T00:00:00Z
Authorization: Bearer {{Gitlab_AccessToken}}


### 