# Gitlab - Projects API
#    https://docs.gitlab.com/ee/api/projects.html
# 
# =========================================================
@project_id={{$dotenv project_id}}


### (如果 projects 很多的話沒有任何意義!!) 列出 GitLab 所有專案
GET {{Gitlab_api_v4}}/projects
Authorization: Bearer {{Gitlab_AccessToken}}


### 查詢 特定 project_id 詳細資訊
GET {{Gitlab_api_v4}}/projects/{{project_id}}
Authorization: Bearer {{Gitlab_AccessToken}}


### 修改 特定 project_id 裡頭的變數設定
PUT {{Gitlab_api_v4}}/projects/{{project_id}}
Authorization: Bearer {{Gitlab_AccessToken}}
Content-Type: application/json

{
    "restrict_user_defined_variables": false
}


### 查詢 特定 project_id 所歸屬的 groups 相關資訊
GET {{Gitlab_api_v4}}/projects/{{project_id}}/groups
Authorization: Bearer {{Gitlab_AccessToken}}



# ============================ Pipelines ============================
### 列出 Pipeline 清單
# https://docs.gitlab.com/ee/api/pipelines.html
GET {{Gitlab_api_v4}}/projects/{{project_id}}/pipelines
    ?page=1
    &per_page=20
    &updated_after=2022-10-19T00:00:00Z
    &order_by=updated_at
    &sort=desc
Authorization: Bearer {{Gitlab_AccessToken}}


### 查詢單一 Pipeline 詳細資訊
@pipelineID=670740966
GET {{Gitlab_api_v4}}/projects/{{project_id}}/pipelines/{{pipelineID}}
Authorization: Bearer {{Gitlab_AccessToken}}


### 