
# 2022Q4 Gitlab 的 OpenAPI
#    https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/openapi/openapi.yaml?_gl=1%2a1gchx6o%2a_ga%2aMTgxODkyOTQ4OS4xNjY0NDUwMzgw%2a_ga_ENFH3X7M5Y%2aMTY2NDY0MTEwNS4yLjEuMTY2NDY0MjM1Ny4wLjAuMA..
#    https://docs.gitlab.com/ee/api/
#    https://docs.gitlab.com/ee/api/api_resources.html
# 
# 
# -----------------------------------------------------------

### 查詢 Gitlab Server 的 Metadata (需要身份驗證)
GET {{Gitlab_api_v4}}/metadata
Authorization: Bearer {{Gitlab_AccessToken}}


### 
GET {{Gitlab_api_v4}}/version
Authorization: Bearer {{Gitlab_AccessToken}}