# Gitlab api
#    https://docs.gitlab.com/ee/api/api_resources.html#group-resources

@group_id={{$dotenv group_id}}


### 查詢 token 有權限訪問的 groups
# https://docs.gitlab.com/ee/api/groups.html#list-groups
GET {{Gitlab_api_v4}}/groups
Authorization: Bearer {{Gitlab_AccessToken}}


### 查詢 特定 group_id 底下的 subgroups
GET {{Gitlab_api_v4}}/groups/{{group_id}}/subgroups
Authorization: Bearer {{Gitlab_AccessToken}}


### 查詢 特定 group_id 底下的 projects
# https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects
GET {{Gitlab_api_v4}}/groups/{{group_id}}/projects?simple=true
Authorization: Bearer {{Gitlab_AccessToken}}