services:
  es01:
    image: elasticsearch:8.15.1
    container_name: es
    hostname: es
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.license.self_generated.type=trial"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    volumes:
      - vol_es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - net_es

networks:
  net_es:
    name: net_es

volumes:
  vol_es:
    name: vol_es