---
kind: pipeline
type: docker
name: Deploy Web

steps:
  - name: build
    image: node:12.14
    commands:
      - npm install
      - npm run-script build
  - name: Deploy
    image: appleboy/drone-scp
    settings:
      host: ${HOST=192.168.2.87}
      username: root
      password:
        from_secret: PASSWD
      port: 22
      strip_components: 1
      source:
        - dist
      target:
        - /var/app/static_web

# drone exec --secret-file=secrets.txt
# 執行 pipeline 的時候需要一些 secrets
# 建構過程, runner 只能訪問 repository(不適合存放secrets) 的內容