version: '3'

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net_traefik
    command:
      - --api.debug=true
      - --api.dashboard=true
      - --api.insecure=true
      - --ping=true
      - --serversTransport.insecureSkipVerify=true
      - --log.level=DEBUG
      # - --log.filePath=/tmp/traefik.log
      # - --accesslog=true
      # - --accesslog.filepath=/tmp/access_traefik.log
      # - --accesslogbufferingsize=100
      - --providers.docker
      # - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

networks:
  net_traefik:
    external: true
