version: '3'

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.10
    restart: always
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    command:
      - --api.insecure=true
      - --providers.docker
      #- "--configfile=/etc/traefik/traefik.yml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./traefik:/etc/traefik/
    networks:
      - net_reverse_proxy

networks:
  net_reverse_proxy:
    name: net_traefik