
services:
  db:
    image: postgres:16.10
    container_name: pg
    hostname: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - vol_pg_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  vol_pg_data:
    name: vol_pg_data
    external: true