# Example taskfile.json
# From: 
#   https://dev.to/stack-labs/introduction-to-taskfile-a-makefile-alternative-h92
version: "3"

vars:
  CONTAINER_IMAGE_NAME: mycontainerimage
  # CONTAINER_IMAGE_TAG: {sh: git-rev parse HEAD}
  CONTAINER_IMAGE: "{{.CONTAINER_IMAGE_NAME}}:{{.CONTAINER_IMAGE_TAG}}"
  # CURRENT: {{now | date "2006-01-02"}}

env:
  AGE: 30

dotenv: ['.env']

tasks:
  hi:
    desc: Say Hi by export
    cmds:
      # export NAME=Tony && task hi
      - echo Hello~ {{.NAME}}, {{.AGE}}
    
  hi2:
    desc: Say Hi by .env
    cmds:
      - echo Hello~ {{.NAME}}

  build:
    desc: Build the container image
    cmds:
      - docker build -t {{.CONTAINER_IMAGE}} -f Dockerfile .

  enter:
    desc: Enter into the build container
    cmds:
      - docker run -it --rm --entrypoint=sh {{.CONTAINER_IMAGE}}

  push:
    desc: Push built image
    cmds:
      - docker push {{.CONTAINER_IMAGE}}
