version: '3.9'

services:
  grafana:
    image: grafana/grafana:7.5.7
    container_name: gra
    hostname: gra
    restart: always
    ports:
      - "3000:3000"
    networks:
      - net_grafana

networks:
  net_grafana:
    name: net_grafana