# https://docs.drone.io/server/provider/gitea/
# https://github.com/auxilincom/deploy-drone/blob/master/local/docker-compose.yml
# gitea + drone-server

version: "3"

services:

  drone-server:
    image: drone/drone:1
    container_name: drone-server
    restart: always
    environment:
      - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_AGENTS_ENABLED=true
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
    volumes:
      - drone_db:/data
    ports:
      - 3001:80
      - 3443:443

volumes:
  drone_db: {}
