global:
  resolve_timeout: 5m

# templates:
#   - '/etc/alertmanager/template/*.tmpl'

route:
  group_interval: 1m
  repeat_interval: 30m # interval to re-alert
  receiver: "slack_hook"

receivers:
  - name: "demo_hook"
    webhook_configs:
      - url: "WEBHOOK_SITE_URL" # https://webhook.site/
        send_resolved: true

  - name: 'slack_hook'
    slack_configs:
    - channel: '#alert'
      api_url: "SLACK_WEBHOOK_URL"
      send_resolved: true
      text: "<!channel> \n {{ .CommonAnnotations.description }}"

  # - name: 'sns_hook'
  #   sns_configs:
