global:
  resolve_timeout: 5m

# templates:
#   - '/etc/alertmanager/template/*.tmpl'

route:
  group_interval: 1m
  repeat_interval: 30m # interval to re-alert
  receiver: "demo_hook"

receivers:
  - name: "demo_hook"
    webhook_configs:
      - url: "https://webhook.site/086c1994-551d-41e1-a1a7-95de45af0f7e" # https://webhook.site/
        send_resolved: true

  # - name: 'sns_hook'
  #   sns_configs:

  # - name: 'slack_hook'
  #   slack_configs:
