global:
  scrape_interval: 20s
  scrape_timeout: 5s
  evaluation_interval: 20s

scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: "10s"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - regex: "container_label_(org|com).+"
        action: labeldrop
      - regex: "container_label_maintainer"
        action: labeldrop

  - job_name: "prometheus"
    # basic_auth:
    #   username: "admin"
    #   password: "xxxxxxxx"
    static_configs:
      - targets: ["localhost:9090"]

  # ###(cadvisor 可以取代此功能, 因此可不配置 docker_sd_configs)
  # - job_name: "docker"
  #   docker_sd_configs:
  #     - host: "host.docker:9323"

rule_files:
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]