global:
  scrape_interval: 20s
  scrape_timeout: 5s
  evaluation_interval: 20s
  # query_log_file: /var/log/prometheus/query.log  # 用來記錄所有的 prometheus query

rule_files:
  - rules_alert.yml
  - rules_record.yml

scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: "10s"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - regex: "container_label_(org|com).+"
        action: labeldrop
      - regex: "container_label_maintainer"
        action: labeldrop

  - job_name: "prometheus"
    basic_auth:
      username: "admin"
      password: "<明碼密碼>" # FIXME: bcrypt(<明碼密碼>) 需要放置於 web.yml
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["docker_host:9100"]
    #file_sd_configs:
    #  - files:
    #      - "node_targets.json"

  #- job_name: "docker" # (cadvisor 可以取代此功能)
  #  docker_sd_configs:
  #    - host: "host.docker:9323" # via TCP Socket
  #    - host: unix:///var/run/docker.sock  # via Unix Socket

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
